<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class StampCodesExport implements FromQuery, WithHeadings, WithMapping, WithStyles, ShouldAutoSize
{
    public function __construct(protected $query) {}

    public function query()
    {
        return $this->query;
    }

    public function headings(): array
    {
        return [
            'Code',
            'Reference Number',
            'Loyalty Card',
            'Branch',
            'Customer Username',
            'Customer Email',
            'Generated By',
            'Status',
            'Type',
            'Used At',
            'Created At',
        ];
    }

    public function map($row): array
    {
        $status = $row->is_expired ? 'Expired' : ($row->used_at ? 'Used' : 'Active');
        $generatedBy = $row->staff?->username ?? $row->user?->email ?? 'N/A';

        return [
            $row->code,
            $row->reference_number ?? 'N/A',
            $row->loyalty_card?->name ?? 'N/A',
            $row->branch?->name ?? 'N/A',
            $row->customer?->username ?? 'Unassigned',
            $row->customer?->email ?? 'N/A',
            $generatedBy,
            $status,
            $row->is_offline_code ? 'Offline' : 'Online',
            $row->used_at ? \Carbon\Carbon::parse($row->used_at)->format('Y-m-d H:i') : 'N/A',
            \Carbon\Carbon::parse($row->created_at)->format('Y-m-d H:i'),
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true]],
        ];
    }
}
